-- TiDB / MySQL schema for Budget Monitoring
-- Run this once on your TiDB database.

CREATE TABLE IF NOT EXISTS budget_records (
  id VARCHAR(191) NOT NULL,
  status VARCHAR(32) NOT NULL,
  namaUser VARCHAR(255) NOT NULL,
  tim VARCHAR(255) NOT NULL,
  periode VARCHAR(64) NOT NULL,
  nilaiTagihan BIGINT NOT NULL,
  noRO VARCHAR(128) NULL,
  tglBAST VARCHAR(64) NULL,
  noBAST VARCHAR(128) NULL,
  status2 VARCHAR(255) NULL,
  emailSoftCopy VARCHAR(255) NULL,
  saNo VARCHAR(128) NULL,
  tglKirimJKT VARCHAR(64) NULL,
  reviewerVendor VARCHAR(255) NULL,
  keterangan TEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
